return {
  {
    "akinsho/bufferline.nvim",
    version = "*",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    event = "VeryLazy",
    keys = {
      { "<Tab>", "<cmd>BufferLineCycleNext<CR>", desc = "Next buffer" },
      { "<S-Tab>", "<cmd>BufferLineCyclePrev<CR>", desc = "Prev buffer" },
      { "<leader>bp", "<cmd>BufferLinePick<CR>", desc = "Pick buffer" },
      { "<leader>bc", "<cmd>BufferLinePickClose<CR>", desc = "Close buffer" },
      { "<leader>b1", "<cmd>BufferLineGoToBuffer 1<CR>" },
      { "<leader>b2", "<cmd>BufferLineGoToBuffer 2<CR>" },
      { "<leader>b3", "<cmd>BufferLineGoToBuffer 3<CR>" },
      { "<leader>b4", "<cmd>BufferLineGoToBuffer 4<CR>" },
      { "<leader>b5", "<cmd>BufferLineGoToBuffer 5<CR>" },
    },
    opts = {
      options = {
        mode = "buffers",
        numbers = "ordinal",
        close_command = "bdelete! %d",
        indicator = {
          style = "icon",
          icon = "▎",
        },
        buffer_close_icon = "",
        modified_icon = "●",
        close_icon = "",
        left_trunc_marker = "",
        right_trunc_marker = "",
        max_name_length = 30,
        max_prefix_length = 15,
        truncate_names = true,
        tab_size = 20,
        diagnostics = false,
        offsets = {
          {
            filetype = "neo-tree",
            text = "File Explorer",
            text_align = "center",
            separator = true,
          },
        },
        color_icons = true,
        show_buffer_icons = true,
        show_buffer_close_icons = true,
        show_close_icon = false,
        show_tab_indicators = true,
        separator_style = "slant",
        enforce_regular_tabs = false,
        always_show_bufferline = true,
        hover = {
          enabled = true,
          delay = 150,
          reveal = { "close" },
        },
        sort_by = "insert_after_current",
      },
    },
  },
}